# Generated by Django 5.0.2 on 2024-03-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_content',
            field=models.TextField(default=''),
        ),
    ]
