# Generated by Django 5.0.2 on 2024-03-08 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_subject_image_subject_subject_subject_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_content',
            field=models.TextField(),
        ),
    ]
