# Generated by Django 5.0.2 on 2024-03-08 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_subject_subject_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_images',
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject_image'),
        ),
    ]
