# Generated by Django 5.0.2 on 2024-03-08 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_subject_subject_images_subject_image_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_content',
        ),
        migrations.AddField(
            model_name='subject_image',
            name='group_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subject_image',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='subject_text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('order', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.subject')),
            ],
        ),
    ]
