# Generated by Django 5.0.2 on 2024-03-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_subject_subject_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_image',
            name='group_number',
        ),
    ]
