# Generated by Django 5.0.2 on 2024-03-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_remove_subject_image_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_image',
            name='group',
            field=models.BooleanField(default=False),
        ),
    ]
