# Generated by Django 5.0.2 on 2024-03-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_subject_image_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_image',
            name='group',
        ),
        migrations.RemoveField(
            model_name='subject_image',
            name='order',
        ),
        migrations.DeleteModel(
            name='subject_text',
        ),
    ]
