# Generated by Django 5.0.2 on 2024-03-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_remove_subject_image_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_contnet',
            field=models.TextField(default=' '),
        ),
    ]
