# Generated by Django 5.0.2 on 2024-03-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_subject_sub_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='sub_subjects',
        ),
        migrations.AddField(
            model_name='subject',
            name='sub_subjects',
            field=models.ManyToManyField(blank=True, null=True, to='mainapp.subject'),
        ),
    ]
