# Generated by Django 5.0.2 on 2024-03-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_alter_subject_main_image_remove_subject_sub_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_subjects',
            field=models.ManyToManyField(blank=True, null=True, related_name='sub_subjects_set', to='mainapp.subject'),
        ),
    ]
