# Generated by Django 5.0.2 on 2024-03-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_alter_subject_sub_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='sub_subjects',
            field=models.ManyToManyField(blank=True, related_name='sub_subjects_set', to='mainapp.subject'),
        ),
    ]
