# Generated by Django 5.0.2 on 2024-03-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0019_alter_subject_sub_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='main_title',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
