# Generated by Django 5.0.2 on 2024-03-20 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_testing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testing',
            name='sub_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.testing'),
        ),
    ]
