# Generated by Django 5.0.2 on 2024-04-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_remove_subject_sub_subjects_subject_sub_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/reports/'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
