# Generated by Django 5.0.2 on 2024-04-27 12:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_alter_profile_image_alter_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='email_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
