# Generated by Django 5.0.2 on 2024-04-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_rename_email_subject_mail_email_reply_mail_replied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='subject',
            field=models.CharField(default='', max_length=255),
        ),
    ]
