# Generated by Django 5.0.2 on 2024-05-03 18:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0036_mail_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_contnet',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
