# Generated by Django 5.0.2 on 2024-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_alter_subject_subject_contnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_contnet',
            field=models.TextField(default=' '),
        ),
    ]
