# Generated by Django 5.0.2 on 2024-05-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_doctor_alter_subject_subject_contnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(default='/default.jpg', upload_to='doctor/%Y/%m/%d'),
        ),
    ]
